services:
  app:
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    # volumes:
    #   - ./:/usr/src/app
    environment:
      - NODE_ENV=production
    command: npm run start

    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000/pingz || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
